### ISSUE TITLE
Connect a device to ODL from GEINOS

### ISSUE THREAD

**Issue by bxy3204** [falhenaki/GEINOS#14]
PUT http://localhost:8181/restconf/config/network-topology:network-topology/topology/topology-netconf/node/new-netconf-device
Headers:

    Accept: application/xml
    Content-Type: application/xml

Body:
<node xmlns="urn:TBD:params:xml:ns:yang:network-topology">
  <node-id>new-netconf-device</node-id>
  <host xmlns="urn:opendaylight:netconf-node-topology">192.168.1.1</host>
  <port xmlns="urn:opendaylight:netconf-node-topology">830</port>
  <username xmlns="urn:opendaylight:netconf-node-topology">admin</username>
  <password xmlns="urn:opendaylight:netconf-node-topology">admin</password>
  <tcp-only xmlns="urn:opendaylight:netconf-node-topology">false</tcp-only>
  
  <reconnect-on-changed-schema xmlns="urn:opendaylight:netconf-node-topology">false</reconnect-on-changed-schema>
  <connection-timeout-millis xmlns="urn:opendaylight:netconf-node-topology">20000</connection-timeout-millis>
  <max-connection-attempts xmlns="urn:opendaylight:netconf-node-topology">0</max-connection-attempts>
  <between-attempts-timeout-millis xmlns="urn:opendaylight:netconf-node-topology">2000</between-attempts-timeout-millis>
  <sleep-factor xmlns="urn:opendaylight:netconf-node-topology">1.5</sleep-factor>
  
  <keepalive-delay xmlns="urn:opendaylight:netconf-node-topology">120</keepalive-delay>
</node>

link to tutorial where this info was taken: http://docs.opendaylight.org/en/stable-nitrogen/user-guide/netconf-user-guide.html

**Comment by falhenaki** [comment]
I can do the wrapper to make the call
Brian will test the call inputting the needed values and get the needed headers and parms

**Comment by falhenaki** [comment]
I pushed a simple python script to models.py, @bxy3204 you can use it to see if we can communicate with the device with no issues.

**Comment by doug-gawne** [comment]
I added the required routing to allow this test script to be run from within the app for now this is the only thing shown after logging in.
