### ISSUE TITLE
SCEP enrollment UI

### ISSUE THREAD

**Issue by bxy3204** [falhenaki/GEINOS#154]
As a User I want to be able to define the SCEP server used by the system

**Comment by falhenaki** [comment]
fields:
set address (string)
username (string)
password (password)

**Comment by bxy3204** [comment]
also need the following fields:
digest-algorithm(choice): md5, sha1,sha256,sha384,sha512
Encryption-algorithm(choice): des_cbc, 3des_cbc, aes128_cbc, aes192_cbc, aes256_cbc
default: sha256, 3des_cbc
