### ISSUE TITLE
Front end bug-continuous redirect to login page when on login page and not logged in

### ISSUE THREAD

**Issue by bxy3204** [falhenaki/GEINOS#204]

**Comment by falhenaki** [comment]
That’s not a bug that’s a feature.

**Comment by bxy3204** [comment]
Login validation should only be done on timeout or component reload, not every second regardless of if we have ever logged in or not.

**Comment by bxy3204** [comment]
user login is now validated on componenetDidMount, which is always called when loading a new page or attempting to add something to the backend.
